### ISSUE TITLE
problema de que no encuentra el id.

### ISSUE THREAD

**Issue by JackER4565** [kellyfabiolafc/store#1]
Kelly !!

ya encontre el problema, es que adentro de la funcion find estas comparando con triple igual (===)

`   const product = products.find((each) => each.id === id);`
   
   y esto falla por que el id que viene de parametros es **STRING** y el id que esta en el objeto es **NUMBER**, entonces el triple igual, que chequea si es de igual valor y tipo falla!!!!!!

sacale un igual y proba:
`   const product = products.find((each) => each.id == id);`

**Comment by kellyfabiolafc** [comment]
Muchas gracias por el consejo Fabri ! Cambié el triple igual === por el doble igual == en la función find, y ahora funciona perfecto. Aprecio mucho la ayuda. Gracias 🤠
